# buildspec.yml
version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - "aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 145023138993.dkr.ecr.ap-south-1.amazonaws.com"
      - "REPOSITORY_URI=145023138993.dkr.ecr.ap-south-1.amazonaws.com/httpd-app" 
      - "IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)"
      - echo "REPOSITORY_URI: ${REPOSITORY_URI}"
      - echo "IMAGE_TAG: ${IMAGE_TAG}"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Writing image definitions file..."
      - printf '[{"name":"httpd-app","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
      - echo "Updating appspec.yml with ECR URI..."
      # Replace the placeholder in appspec.yml for the Docker image name
      - sed -i "s|145023138993.dkr.ecr.ap-south-1.amazonaws.com/httpd-app:latest|$REPOSITORY_URI:latest|g" appspec.yml
      - cat appspec.yml # Verify the change
artifacts:
  files:
    - appspec.yml
    - scripts/**/*
  discard-paths: no
